# Site settings
title: kevin mchugh's home on the world wide web
email: kev AT this domain
description: > # this means to ignore newlines until "baseurl:"
  i don't really know why i have a website any better than you do
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevinmchugh.me" # the base hostname & protocol for your site
twitter_username: krmchugh
github_username:  kevinmchugh

# Build settings
markdown: kramdown
gems:
  - jemoji